config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'projects#index'

  resources :projects, only: [:create]

  get "admin", to: "admin#index"
  delete "reset_projects", to: "projects#destroy_all"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_memberships, dependent: :destroy

  def member_names
    project_memberships.map(&:user_name)
  end
end

app/models/project_membership.rb
class ProjectMembership < ApplicationRecord
  belongs_to :project
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def create
    @project = Project.create!({
      description: params[:project][:description]
    })
    redirect_to(action: "index")
  end

  def destroy_all
    Project.destroy_all
    flash[:success] = "All projects were deleted"
    redirect_to(admin_path)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.erb
<h1>Welcome Admin</h1>

<% if flash[:success] %>
  <div><%= flash[:success] %></div>
<% end %>

<%= link_to "All projects", root_path %>
<%= link_to "Delete projects", reset_projects_path, method: "delete"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Waza Board</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_show.erb
<li class="project">
  <div class="project-description"><%= project.description %></div>
  <div class="project-members"><%= project.member_names.join ", " %></div>
</li>

app/views/projects/index.erb
<header>
  <h1>Waza Board</h1>
</header>

<section>
  <div class="module__form">
    <h3>Add a Project</h3>
    <%= form_for :project, url: projects_path do |f| %>
      <%= f.text_field :description %>
      <%= f.submit "Create Project" %>
    <% end %>
  </div>
</section>

<section>
  <h3>Active Projects</h3>
  <ul class="project-list">
    <% @projects.each do |project| %>
      <%= render partial: "projects/show", locals: {project: project} %>
    <% end %>
  </ul>
</section>

<footer>
  <h1 class="project-count">There are currently <%= @projects.count %> active projects.</h1>
</footer>